name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-2

      - name: Create SSH Private Key File
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > /tmp/EC2_SSH_KEY.pem
          chmod 600 /tmp/EC2_SSH_KEY.pem

      - name: Debug SSH Key File (Optional)
        run: |
          ls -l /tmp/EC2_SSH_KEY.pem
          file /tmp/EC2_SSH_KEY.pem
          wc -l /tmp/EC2_SSH_KEY.pem

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/EC2_SSH_KEY.pem ubuntu@18.117.181.101 "echo 'SSH Connection Successful'" || exit 1

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/EC2_SSH_KEY.pem ubuntu@18.117.181.101 << 'EOF'
          set -e  # Stop execution if any command fails
          cd /var/www/html
          git reset --hard HEAD  # Ensure a clean working directory
          git pull origin main
          sudo systemctl restart nginx
          echo "Deployment successful!"
          EOF
